# ---------- Build stage ----------
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o pocketbase-app .

# ---------- Runtime stage ----------
FROM alpine:3.23

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/pocketbase-app .

VOLUME ["/app/pb_data"]

EXPOSE 8090

CMD ["./pocketbase-app", "serve", "--http=0.0.0.0:8090"]